### PR TITLE
Prepare for Nullable `ASTHelpers.getSymbol`

### PR DESCRIPTION
**Pull request by XN137**
for discussion from https://github.com/uber/NullAway/pull/729#issuecomment-1418267121

one could argue the required effort isn't that much in the nullaway codebase itself, but of course it is up to you

i am also asking in https://github.com/google/error-prone/issues/3760 whether the annotation is intentionally missing or not

### CODE REVIEW

**Comment by msridhar** [comment]
I know this is still a draft, but given that https://github.com/google/error-prone/issues/3760 was fixed, I'm open to merging a PR like this one.  And we should add a comment to delete the library model once we update to the next release of Error Prone.

**Comment by XN137** [comment]
@msridhar thanks for the feedback, what do you think is the best way to handle the failing `testNullawayRelease` test?
do we need an option to disable this model when checking earlier nullaway releases?

**Comment by msridhar** [comment]
> @msridhar thanks for the feedback, what do you think is the best way to handle the failing `testNullawayRelease` test?
> do we need an option to disable this model when checking earlier nullaway releases?

One option is to not add the model, just the fixes.  If we assume there will be an Error Prone release in the relatively near future, we'll get the annotation then.  And since the benchmark is compiled against a fixed version of Error Prone, that shouldn't break the JMH test.

I think adding an option to disable the model just for the benchmark is a bit overly complex.  And, I don't want to disable the benchmark.  So maybe no model is the best solution?

**Comment by XN137** [comment]
i'll wait for the new errorprone release and then rebase without the model

**Comment by XN137** [comment]
rebased after the other PR went in

1st commit shows that CI passes with the model but 2nd commit removes it

we could review/merge this now or wait until the next errorprone version is out

@msridhar WDYT ?

**Review by msridhar — APPROVED** [review]
I think we can get these changes in now, before the next EP release

**Pull request merged**
