### PR TITLE
[Gradle] JDK17 targets shouldn't try to build on older JDKs

### PR DESCRIPTION
**Pull request by lazaroclapp**
Not sure why this wasn't breaking before, but after the latest JDK update, these two targets will fail to build when `./gradlew publishtoMaven[Local|Central]` is attempted on a JDK < 17. Recall that we are still releasing by building with JDK8 for compatibility reasons.

### CODE REVIEW

**Comment by lazaroclapp** [comment]
This alone doesn't seem enough to fix `publishToMavenLocal` after all the recent gradle changes, seeing the following follow up issue:
```
* What went wrong:
Execution failed for task ':jar-infer:android-jarinfer-models-sdk31:publishMavenPublicationToMavenLocal'.
> Failed to publish publication 'maven' to repository 'mavenLocal'
   > Invalid publication 'maven': artifact file does not exist: '/home/user/NullAway/jar-infer/android-jarinfer-models-sdk31/build/publications/maven/pom-default.xml.asc'
```

**Comment by msridhar** [comment]
On an M1 Mac, I cannot reproduce these problems.  Even on the `master` branch, `./gradlew publishToMavenLocal` succeeds, on JDKs 8, 11, and 17.  @lazaroclapp can you try `./gradlew clean publishToMavenLocal --no-build-cache`?

**Comment by lazaroclapp** [comment]
This one doesn't seem necessary right now, after #767. Might be part of fixing #768, but closing for now.

**Comment by lazaroclapp** [comment]
Looks like I spoke too soon, this still reproduces on a Linux Devpod, with JDK 11 or 8. It doesn't happen on Mac OS...

**Comment by lazaroclapp** [comment]
**Update** (for documentation purposes):

This seems to be ultimately due to where our Linux install/container puts the different JDKs available to it. It is not a path where the gradle toolchain mechanism looks into by default. An easy fix, as documented [here](https://docs.gradle.org/current/userguide/toolchains.html#sec:custom_loc), is to add the paths to a `org.gradle.java.installations.paths` property on the user-home level gradle.properties file (`~/.gradle/gradle.properties`), which is the fix we are implementing internally. This means no change is needed or desired in NullAway itself and this can be closed.

**Pull request closed without merging**
