### PR TITLE
435-more common libraries and files as null or not null

### PR DESCRIPTION
**Pull request by pablogrisafi1975**
Thank you for contributing to NullAway!

Please note that once you click "Create Pull Request" you will be asked to sign our [Uber Contributor License Agreement](https://cla-assistant.io/uber/NullAway) via [CLA assistant](https://cla-assistant.io/).

Before pressing the "Create Pull Request" button, please provide the following:

  - [ ] A description about what and why you are contributing, even if it's trivial.
  Small change including more libraries/methods in LibraryModelsHandler.java, some for sparkjava, some from Spring, some from apache commons lang

  - [ ] The issue number(s) or PR number(s) in the description if you are contributing in response to those.
  Issue is https://github.com/uber/NullAway/issues/435, created by myself

  - [ ] If applicable, unit tests.
  Could not find a way to unit to this changes, so I made a project with possible and impossible NPE to see if my modified NullAway version worked. Seems to be working, the project is https://github.com/pablogrisafi1975/NullAway-tests.

### CODE REVIEW

**Comment by lazaroclapp** [comment]
> Could not find a way to unit to this changes, so I made a project with possible and impossible NPE to see if my modified NullAway version worked.

You could test this changes by modifying e.g. `NullAwayNativeModels.java` under `nullaway/src/test/resources/...`. In particular, we have some sample code testing native models for `StringUtils.isEmpty` [here](https://github.com/uber/NullAway/blob/master/nullaway/src/test/resources/com/uber/nullaway/testdata/NullAwayNativeModels.java#L355).

Whenever you expect an issue to be raised, you just need to write a comment of the form `// BUG: Diagnostic contains: [partial text in the NullAway warning]`

We'd love to have those test cases included with this PR. That said, I am not sure if we should require them for all of these methods. @msridhar , thoughts?

**Comment by msridhar** [comment]
@pablogrisafi1975 have you been able to test out these changes to see that they work as expected on your code base?  If so, I am ok with landing this without additional tests.

**Comment by pablogrisafi1975** [comment]
> @pablogrisafi1975 have you been able to test out these changes to see that they work as expected on your code base? If so, I am ok with landing this without additional tests.

What I did and seems to be working: 
I made the changes in the PR, installed in my local maven repository with `gradlew clean install`, and created a new project (https://github.com/pablogrisafi1975/NullAway-tests) that uses

                         <path>
                            <groupId>com.uber.nullaway</groupId>
                            <artifactId>nullaway</artifactId>
                            <version>0.8.1-SNAPSHOT</version>
                        </path>

Then I run `mvn clean verify` and I got the expected messages, a lot of

       [NullAway] dereferenced expression str is @Nullable

What I wasn't able to do: compile the NullAway project with `graddle clean test`

first I got an error because of `import com.sun.istack.internal.NotNull`, I remove the annotation and the import just to see what happen and got lots of

    error: package jdk.internal.org.objectweb.asm.tree does not exist
    import jdk.internal.org.objectweb.asm.tree.ClassNode;

Honestly, I'm not being able to understand what's going on. Probably  is my ignorance abut gradle, combined with the strange tests this library needs to have.

**Comment by lazaroclapp** [comment]
> > @pablogrisafi1975 have you been able to test out these changes to see that they work as expected on your code base? If so, I am ok with landing this without additional tests.
> 
> What I did and seems to be working:
> I made the changes in the PR, installed in my local maven repository with `gradlew clean install`, and created a new project (https://github.com/pablogrisafi1975/NullAway-tests) that uses
> 
> ```
>                      <path>
>                         <groupId>com.uber.nullaway</groupId>
>                         <artifactId>nullaway</artifactId>
>                         <version>0.8.1-SNAPSHOT</version>
>                     </path>
> ```
> 
> Then I run `mvn clean verify` and I got the expected messages, a lot of
> 
> ```
>    [NullAway] dereferenced expression str is @Nullable
> ```
> 
> What I wasn't able to do: compile the NullAway project with `graddle clean test`
> 
> first I got an error because of `import com.sun.istack.internal.NotNull`, I remove the annotation and the import just to see what happen and got lots of
> 
> ```
> error: package jdk.internal.org.objectweb.asm.tree does not exist
> import jdk.internal.org.objectweb.asm.tree.ClassNode;
> ```
> 
> Honestly, I'm not being able to understand what's going on. Probably is my ignorance abut gradle, combined with the strange tests this library needs to have.

Out of curiosity, do you get that same issue with `./gradlew clean test`? 

In any case, that seems like an issue testing JarInfer, not the core NullAway checker and CI checks above pass. You could, if you wanted to, run `./gradlew :nullaway:build` to build (and run tests) for *only* NullAway proper, ignoring the integration tests and JarInfer. But this is not necessary on our end, since CI above already ran that successfully.

I am merging this PR for now, given that it works in the test project, CI passes, and the change is very low risk.

Thanks for contributing to NullAway, @pablogrisafi1975 !

**Review by lazaroclapp — APPROVED** [review]
LGTM.

**Comment by pablogrisafi1975** [comment]
> Out of curiosity, do you get that same issue with ./gradlew clean test?

Yes, I just tried and got 

```
> Task :jar-infer:jar-infer-lib:compileJava FAILED
C:\Users\Pablo\git\NullAway\jar-infer\jar-infer-lib\src\main\java\com\uber\nullaway\jarinfer\DefinitelyDerefedParams.java:38: error: package com.sun.istack.internal does not exist
import com.sun.istack.internal.NotNull;
                              ^
C:\Users\Pablo\git\NullAway\jar-infer\jar-infer-lib\src\main\java\com\uber\nullaway\jarinfer\DefinitelyDerefedParams.java:130: error: cannot find symbol
  @NotNull
```
And once I removed the `@NotNull` and import, I got a 

```
C:\Users\Pablo\git\NullAway\jar-infer\jar-infer-lib\src\test\java\com\uber\nullaway\jarinfer\AnnotationChecker.java:212: error: cannot find symbol
    for (AnnotationNode annotationNode : annotations) {
```


Maybe it's a windows problem? Family computer, sorry. Maybe com.sun.istack.internal is an undeclared dependency you all have in your classpath? Maybe the wrong JVM?

**Comment by msridhar** [comment]
Thanks, @pablogrisafi1975.  Maybe once we complete the transition to GitHub Actions, we can run a Windows CI job to see if there's a general Windows issue or one more specific to your setup.

**Pull request merged**
