### PR TITLE
Update to WALA 1.5.4

### PR DESCRIPTION
**Pull request by msridhar**
Update to the latest WALA version.  Also, switch class hierarchy construction to use `makeWithRoot` which is more fully-baked than what we used before; see wala/WALA#377.

@lazaroclapp @navahgar this probably requires some internal testing before landing, to make sure JarInfer still works properly.

### CODE REVIEW

**Comment by lazaroclapp** [comment]
Looks good, but I want to land and test #334 first, then checkout this one, rebase on top of that and test it internally. After that, if all goes well, we can land this one and cut a release with the new WALA and working AAR/JAR bytecode rewriting support.

**Comment by lazaroclapp** [comment]
Seeing a ton of messages like `WARNING: java_runtime_dir null in wala.properties is invalid.  Using boot class path instead.` internally for this, does that file need to exist when running JarInfer after the WALA 1.5.3 upgrade?

**Comment by msridhar** [comment]
@lazaroclapp that message is just for informative purposes, it should not affect the running of the tool.  I'm not sure why those messages weren't getting printed before.  If you like, I can try to get rid of the message and cut a new WALA release.  Would that be helpful?

**Comment by lazaroclapp** [comment]
> @lazaroclapp that message is just for informative purposes, it should not affect the running of the tool. I'm not sure why those messages weren't getting printed before. If you like, I can try to get rid of the message and cut a new WALA release. Would that be helpful?

Is there a parameter we can pass when initializing WALA inside JarInfer to silence this? The problem is one of CI log pollution and also it prints during local buck builds which isn't a great UX. I could redirect JarInfer's CLI output to `/dev/null` or some other log, but I kinda would want to get any real issues to show up in stdout, but not this warning :)

**Comment by msridhar** [comment]
@lazaroclapp I've cut a new WALA release that should kill the log noise and updated this PR to that release.  Let me know if it works

**Pull request merged**
