### PR TITLE
Upstream API Analysis

### PR DESCRIPTION
**Pull request by nimakarimipour**
This PR enables [Annotator](https://github.com/nimakarimipour/NullAwayAnnotator) to compute effect of making a method `@Nullable` in target module on downstream dependencies without injecting any annotations. List of methods in upstream depencencies is given to `NullAway` as a `.tsv` file format which every row is the containing class and method symbol of the method declared in the upstream dependency.

While analysing the source code, `NullAway` will assume all methods of upstream dependency given in the list returns `@Nullable`.

To enable this feature, in the `FixSerializationConfig`, `apiAnalysisFromUpstreamDependencyEnabled` should be set to `true` along the path to the `.tsv` file which contains the list of methods in upstream dependency in `upstreamDependencyAPIInfoFile`.

The equivalent of the flags above in the `.xml` config files are: 
```xml
<serialization>
     <apiAnalysisFromUpstreamDependency "active"=true, "path"="path_to_file.tsv">
</serialization>
```

### CODE REVIEW

**Comment by msridhar** [comment]
Very cool! I have a question. Could we do this instead via a `LibraryModel` that reads the list of methods? Then we would just stick the custom `LibraryModel` in the processor path. I'm wondering if we can achieve the same thing without modifying NullAway.

**Comment by nimakarimipour** [comment]
> Very cool! I have a question. Could we do this instead via a `LibraryModel` that reads the list of methods? Then we would just stick the custom `LibraryModel` in the processor path. I'm wondering if we can achieve the same thing without modifying NullAway.

Hi @msridhar thank you very much for the comment, I am not familiar with `LibraryModels` , I will look into this and get back to you. Thank you.

**Comment by msridhar** [comment]
Sure! @lazaroclapp can help 🙂

**Comment by msridhar** [comment]
One thing is I'm not sure if a library model will work on annotated code. But even if not, we could add a flag just to enable that.

**Comment by nimakarimipour** [comment]
@msridhar @lazaroclapp I just had another look on this PR, it seems that what handlers suggest is only considered as a hint and it will be overridden by dataflow analysis results. Now please assume that `Foo.bar()` is an upstream method and consider the example below:
```java
Foo foo = new Foo();
foo.bar().toString();
```
While processing `foo.bar()` we can successfully inform NullAway that `Foo.bar()` is an upstream method and make it `Nullable` which ends to entry (`AccessPath root(foo) element(bar()) as Nullable`) in Null-ness store. However while processing `.toString()` part of the expression at [line 735](https://github.com/uber/NullAway/blob/2c98f2bb5d54d15328775b297c8fd7481e79ff5a/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java#L735) we forcefully update the store with entry `AccessPath root(foo) element(bar()) as Non-null` to set the receiver as `Non-null`. This new entry will override any other decisions made by handlers in future and will fail the test. This PR may need to modify other parts of `NullAway` outside handlers. Please let me know if I am wrong about this.

**Comment by msridhar** [comment]
It is correct to update the access path to non-null _after_ the call, since the call can only succeed with a non-null receiver. The receiver should still be nullable _before_ the call which should lead to NullAway reporting an error.

**Comment by nimakarimipour** [comment]
> It is correct to update the access path to non-null _after_ the call, since the call can only succeed with a non-null receiver. The receiver should still be nullable _before_ the call which should lead to NullAway reporting an error.

@msridhar Yes sure, the receiver is indeed nullable before the call and it generates a `NullAway` error successfully. However the test case requires two errors to be reported by NullAway to pass. Please see the example below:
```java
1. Foo foo = new Foo();
2. foo.bar().deref(); // Should see NullAway error which is successfully reported.
3. Object nullableBar = foo.bar();
4. nullableBar.deref(); // Should see NullAway error which is Not reported.
```

Analyzing `deref()` at line 2 on , will lead to entry (`AccessPath [root = foo, element = bar()], Nonnull`) to make the receiver of `deref()` non-null.
Therefore when analyzing line 3, handler hints `foo.bar()` to be `nullable`, but because of the already existing entry in data flow store, it is neglected and `nullableBar` will be non-null and no error will be reported on line 4. Would you please tell me if I should work on introducing a new hint type (e.g. `Force-Nullable`) or follow a different approach ? Thank you very much.

**Comment by msridhar** [comment]
For your example I would argue there should be _no_ error on line 4.  Everywhere else in NullAway we assume that method calls are deterministic by default.  If `foo.bar()` is deterministic, then at line 3 it cannot return `null`, so line 4 is safe.  We want upstream API analysis to show the same potential errors that NullAway would report, not a different set.  So maybe you need to split your test case into 2?

**Comment by nimakarimipour** [comment]
> For your example I would argue there should be _no_ error on line 4. Everywhere else in NullAway we assume that method calls are deterministic by default. If `foo.bar()` is deterministic, then at line 3 it cannot return `null`, so line 4 is safe. We want upstream API analysis to show the same potential errors that NullAway would report, not a different set. So maybe you need to split your test case into 2?

Thank you very much for the suggestion, it makes sense to me now, I will split into two different tests.

**Comment by nimakarimipour** [comment]
Hi all @msridhar @lazaroclapp after the discussion we had here, I decided to split the test case into two separate test cases and this PR now passes all tests successfully and is ready for another review. I am also adding @ketkarameya as a reviewer on this PR.

We currently handle upstream api analysis through a handler, please let me know if we want to switch using `LibraryModels` Thank you.

**Comment by msridhar** [comment]
I prefer investigating the `LibraryModel` approach to see if we can get it to work.  I don't think we should need another handler for this.

**Comment by msridhar** [comment]
I looked into this, and the relevant code for library models is here:

https://github.com/uber/NullAway/blob/2c98f2bb5d54d15328775b297c8fd7481e79ff5a/nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java#L110-L112

So right now library models only apply to unannotated code.  But, I think we could extend things (maybe with a flag) so that at least some (or even all?) library models apply to annotated code.  Then, all the rest of the logic of this PR could be shifted to a new library model, that doesn't even need to live in the NullAway repo.

BTW, @nimakarimipour here are the docs on library models:

https://github.com/uber/NullAway/wiki/Configuration#library-models

**Comment by nimakarimipour** [comment]
> > I looked into this, and the relevant code for library models is here:
> > https://github.com/uber/NullAway/blob/2c98f2bb5d54d15328775b297c8fd7481e79ff5a/nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java#L110-L112
> > 
> > So right now library models only apply to unannotated code. But, I think we could extend things (maybe with a flag) so that at least some (or even all?) library models apply to annotated code. Then, all the rest of the logic of this PR could be shifted to a new library model, that doesn't even need to live in the NullAway repo.
> > BTW, @nimakarimipour here are the docs on library models:
> > https://github.com/uber/NullAway/wiki/Configuration#library-models
> 
> Thank you very much for the instructions, I am currently studying them and will update this PR as soon as possible.

@msridhar I looked into this, and I am now familiar with how it works, however I am not sure yet what is best way to facilitate the communication between `Annotator` and `NullAway` with this approach. I will get back to this as soon as I find a good way.

**Comment by lazaroclapp** [comment]
Ok, just going by the discussion so far:

> > We want upstream API analysis to show the same potential errors that NullAway would report, not a different set. So maybe you need to split your test case into 2?

> Thank you very much for the suggestion, it makes sense to me now, I will split into two different tests.

This is the correct and cleanest way to do it, but I will also point out it doesn't need to be two different unit tests. Just different methods within the same unit test would have the same effect. For now, splitting is the right call, but if you have to test a dozen of related variations, then a single test case with each as a different method within the "sample" code, works to.

> [Re: Library Models vs Handler discussion]

I think using Library Models makes sense, both to minimize upstream changes and also given that we have there a battle-tested API for overriding method information. That said, this will require somewhat more work to integrate with our build. Also, note that, ultimately, Library Models use LibraryModelsHandler, so the lower-level API is the handler API. Will share a document internally in a bit to continue this discussion.

**Comment by lazaroclapp** [comment]
Closing based on the discussion above and offline, in favor of the approach of using custom Library Models and allowing those models to override nullability for annotate/first-party code (see #624)

**Pull request closed without merging**
