### PR TITLE
Update to WALA 1.6.1 and remove ability to build on JDK 8

### PR DESCRIPTION
**Pull request by msridhar**
WALA now runs on JDK 17.  So, with this update, we can run our full build on JDK 17, including JarInfer.  Since WALA has required JDK 11 since version 1.6.0, JarInfer now requires a JDK 11 VM to run, and will no longer run on JDK 8.  In order to get everything to build with this new dependence, we have removed support for building on JDK 8.  NullAway itself will still run as part of a JDK 8 build (and it still tested there, see #778), but running JarInfer now requires JDK 11.  Much of this PR is cleanup enabled by removing support for building on JDK 8.

### CODE REVIEW

**Comment by msridhar** [comment]
This PR will take a bit more work, so converting back to draft.  We currently cut release artifacts on JDK 8.  In order to make this change, we'll need to switch things up so we can cut release artifacts on JDK 11 (or 17) that are compatible with JDK 8.  At that point, we may as well stop supporting building NullAway on JDK 8 altogether (we can still _test_ on JDK 8 using toolchains).  Anyway, will think about how we can make this change incrementally.

**Comment by msridhar** [comment]
Will undraft this after #778 lands

**Review by lazaroclapp — COMMENTED** [review]
It looks good to me. I probably will want to test this internally as soon as both this and #778 land. I assume the process is just to build a local release but do so with JDK11 as the default system `javac`? Anything else to test?

**Review by lazaroclapp — APPROVED** [review]

**Comment by msridhar** [comment]
> It looks good to me. I probably will want to test this internally as soon as both this and #778 land. I assume the process is just to build a local release but do so with JDK11 as the default system `javac`? Anything else to test?

Yes, after this lands, building a local release (or running `./gradlew build`) will only work on JDK 11+.  Using any JDK version 11 or newer should work for building a release; it doesn't have to be 11.  I would specifically test that any workflows involving JarInfer still run correctly.

**Pull request merged**
