### PR TITLE
Build latest Caffeine on CI

### LINKED ISSUE #1110: Set up a CI job testing with Caffeine
Caffeine is a current user of JSpecify mode, and also has a lot of interesting code patterns that may not be covered by our unit tests.  It would be great if we could add a CI job that runs on PRs that would check that the latest Caffeine git SHA builds successfully.  At first we could just make sure there are no crashes, though eventually it would be good to also somehow check to see that any new warnings are sensible.

@ben-manes any thoughts on this?  Right now I do this testing locally by building a NullAway snapshot, changing the NullAway version to the snapshot version in Caffeine's `libs.versions.toml`, and patching `errorprone.caffeine.gradle.kts` to pick up the snapshot with:

```
repositories {
  mavenCentral()
  mavenLocal()
}
```

We could just do this patching in our CI job to start.  But maybe there's a better way.

### PR DESCRIPTION
**Pull request by msridhar**
Fixes #1110 

We can see how this goes for some time before making it a required job.

### CODE REVIEW

**Comment by yuxincs** [comment]
This is pretty cool! 

BTW we have a similar job in NilAway that posts the diff of diagnostics produced by NilAway on stdlib on HEAD vs main for each PR: https://github.com/uber-go/nilaway/blob/main/.github/workflows/golden-test-run.yml

Example: https://github.com/uber-go/nilaway/pull/281#issuecomment-2351988905

We have generally found this to be very useful (although it's partly because NilAway is less mature)

**Review by yuxincs — APPROVED** [review]

**Comment by msridhar** [comment]
> This is pretty cool!
> 
> BTW we have a similar job in NilAway that posts the diff of diagnostics produced by NilAway on stdlib on HEAD vs main for each PR: https://github.com/uber-go/nilaway/blob/main/.github/workflows/golden-test-run.yml
> 
> Example: [uber-go/nilaway#281 (comment)](https://github.com/uber-go/nilaway/pull/281#issuecomment-2351988905)
> 
> We have generally found this to be very useful (although it's partly because NilAway is less mature)

Very cool!  I think once this bakes a bit we could implement some similar logic here.  We would just have to grep out the NullAway warnings from the Gradle build output, though possibly we could just use NullAway's serialization support (thus far used only for NullAway Annotator) to make things more robust.

**Comment by ben-manes** [comment]
> We would just have to grep out the NullAway warnings from the Gradle build output

You can use [problem-matcher.json](https://github.com/ben-manes/caffeine/blob/master/.github/problem-matcher.json) to annotate the pr. Caffeine’s build should fail unless you decide to mark the gha step as continue-on-error.

**Comment by msridhar** [comment]
> > We would just have to grep out the NullAway warnings from the Gradle build output
> 
> You can use [problem-matcher.json](https://github.com/ben-manes/caffeine/blob/master/.github/problem-matcher.json) to [annotate](https://github.com/ben-manes/caffeine/blob/88d58ca132d3328c6499edadd07e7f575516a946/.github/actions/run-gradle/action.yml#L80) the pr. 

Very cool!  From what I'm reading, problem matchers help to annotate source code in the PR.  But here, we have a PR on NullAway, and the errors / warnings we would be looking for would be reported on Caffeine's code.  Would this approach still work?

> Caffeine’s build should fail unless you decide to mark the gha step as continue-on-error.

Ah ok, so NullAway is running at error level now, cool!  That makes things easier, we can just look for a job failure.

**Comment by ben-manes** [comment]
> Would this approach still work?

I believe it would simply be unlinked to the file but still be an annotation attached to the pr. It might look like the ones you have currently wrt the pending ubuntu upgrade.

Screenshot 2024-12-23 at 2 12 23 PM

**Pull request merged**
