### PR TITLE
Bump Checker dataflow to 3.16.0

### PR DESCRIPTION
**Pull request by msridhar**
This pulls in https://github.com/typetools/checker-framework/pull/4748 which should give us a perf win

### CODE REVIEW

**Comment by msridhar** [comment]
On our single jmh benchmark, before:
```
Benchmark                   Mode  Cnt  Score   Error  Units
CaffeineBenchmark.compile  thrpt   25  2.189 ± 0.011  ops/s
```
After:
```
Benchmark                   Mode  Cnt  Score   Error  Units
CaffeineBenchmark.compile  thrpt   25  2.276 ± 0.020  ops/s
```
That's a roughly 4% speedup in bottom-line compile time!  Of course, real-world wins will be much less, since this benchmark only runs NullAway and no other Error Prone checks, no annotation processors, etc.

**Comment by msridhar** [comment]
I'll also note that the speedup comes from faster CFG construction for code containing lambdas.  So code bases without much use of lambdas won't see much difference.

**Review by lazaroclapp — APPROVED** [review]
LGTM. Once this lands, I'll try to cut a release this week.

**Review by lazaroclapp — APPROVED** [review]
LGTM. Once this lands, I'll try to cut a release this week.

**Pull request merged**
