### PR TITLE
Switch from mvn-push script to gradle-maven-publish-plugin

### PR DESCRIPTION
**Pull request by lazaroclapp**
Rather than maintaining our own `gradle-mvn-push.gradle` copy,
let's depend upon an existing plug-in, should help avoid
common issues when publishing maven artifacts (such as #456).

### CODE REVIEW

**Comment by lazaroclapp** [comment]
Manual test plan: Running internal testing with a `-LOCAL` version. Also, uploaded a signed build to Sonatype with a different name, but it will remain unpublished.

**Review by msridhar — APPROVED** [review]
LGTM!  And the test plan sounds good

**Comment by lazaroclapp** [comment]
Not quite ready to land yet, `jar-infer-cli` is not a properly shadowed fat jar with this change, which causes a problem with circular dependencies when jarinfer is used to analyze e.g. Guava...

**Comment by lazaroclapp** [comment]
C.I. and manual test plan all green. Landing now!

**Pull request merged**
