### PR TITLE
Run CI only on PRs and pushes to master (reduce job queuing)

### PR DESCRIPTION
**Pull request by lazaroclapp**

### CODE REVIEW

**Comment by lazaroclapp** [comment]
This ran only Travis CI, so it's still not what we want, unfortunately.

**Comment by msridhar** [comment]
Looks like we got a weird error from GH Actions: https://github.com/uber/NullAway/actions/runs/521677465

**Comment by lazaroclapp** [comment]
Ok, yeah, I think I messed up the yml. It's running now (for `pull_request`). Seems to be working now.

**Review by msridhar — APPROVED** [review]
The change looks fine.  The only thing is that if we as NullAway devs want to run CI on a branch without creating a PR, we just need to do it on a fork.  But that's fine with me

**Comment by lazaroclapp** [comment]
If we have a major non-master branch under development (say `jspecify`), we can always add it to the list for the script. Generally, I think we have been building everything on PRs, so...

**Pull request merged**
